# vim:ts=2:sw=2:et:ai:sts=2
---

- name: _tina_restart_promtail
  ansible.builtin.service:
    name: promtail
    state: restarted

- name: _tina_reload_ferm
  ansible.builtin.service:
    name: ferm
    state: reloaded
