# vim:ts=2:sw=2:et:ai:sts=2
---
# =============================================================================
# Reusable defaults for ACME (letsencrypt) clients.
# =============================================================================

# Until a role/playbook is written, this is only informative.
dehydrated__enable: true

apt__packages_to_install__acme:
  - dehydrated
apt__packages_to_install__acme_apache: |-
  {{ ['dehydrated-apache2'] if apache2__enable else [] }}
