# vim:ts=2:sw=2:et:ai:sts=2
---
# =============================================================================
# Reusable defaults for Prometheus alertmanager servers.
# =============================================================================

apt__packages_to_install__alertmanager:
  - prometheus-alertmanager
apt__services_to_enable__alertmanager:
  - prometheus-alertmanager
apt__services_to_start__alertmanager:
  - prometheus-alertmanager

ferm__services__alertmanager:
  alertmanager:
    dport: 9093
    proto: tcp
    saddr: '{{ internal_networks }}'

  alertmanager-gossip:
    dport: 9094
    proto: tcp
    saddr: '{{ internal_networks }}'
