# vim:ts=2:sw=2:et:ai:sts=2
---
# =============================================================================
# Reusable defaults for Bind servers.
# =============================================================================

apt__packages_to_install__bind:
  - bind9
  - bind9-dnsutils
  - bind9-utils
apt__services_to_enable__bind:
  - named
apt__services_to_start__bind:
  - named

ferm__services__bind:
  domain:
    dport: domain
    proto: [udp, tcp]

bind_config__conf_files: '{{ inventory_dir }}/../files/bind/*'
