# vim:ts=2:sw=2:et:ai:sts=2
---
# =============================================================================
# Additional APT sources for roles using non-official repositories.
# =============================================================================

apt__use_grafana_repo: |-
  {{
    (
      grafana__enable | bool,
      loki__enable | bool,
      promtail__enable | bool,
    ) is any
  }}
apt__custom_sources__grafana: |-
  {{ _apt_grafana_repo if apt__use_grafana_repo else {} }}
apt__trusted_keys__grafana: |-
  {{ _apt_grafana_key if apt__use_grafana_repo else {} }}

_apt_grafana_repo:
  grafana:
    mirror: https://packages.grafana.com/oss/deb
    distro: stable
    components: main

_apt_grafana_key:
  grafana: |
    mQGNBGTnhmkBDADUE+SzjRRyitIm1siGxiHlIlnn6KO4C4GfEuV+PNzqxvwYO+1rmcKlGDU0ugo8
    ohXruAOC77Kwc4keVGNU89BeHvrYbIftz/yxEneuPsCbGnbDMIyCk44UOetRtV9/59Gj5YjNqnsZ
    Cr+e5D/JfrHUJTTwKLv88A9eHKxskrlZr7Un7j3iEf3NChlOh2Zk9Wfk8IhAqMMTferU4iTIhQk+
    5fanShtXIuzBaxU3lkzFSG7VuAH4CBLPWitKRMn5oqXUE0FZbRYL/6Qz0Gt6YCJsZbaQ3Am7FCwW
    Cp9+ZHbR9yU+bkK0Dts4PNx4Wr9CktHIvbypT4Lk2oJEPWjcCJQHqpPQZXbnclXRlK5Ea0NVpaQd
    GK+vJS4HGxFFjSkvTKAZYgwOk93qlpFeDML3TuSgWxuw4NIDitvewudnaWzfl9tDIoVSBb16nwJ8
    bMDzovC/RBE14rRKYtMLmBsRzGYHWd0NnX+FitAS9uURHuFxghv9GFPheTaXvc4glM94HBUAEQEA
    AbQmR3JhZmFuYSBMYWJzIDxlbmdpbmVlcmluZ0BncmFmYW5hLmNvbT6JAdQEEwEKAD4WIQS1Oud7
    rbYwpoMEYAWWP6J3EEWFRQUCZOeGaQIbAwUJA8JnAAULCQgHAgYVCgkICwIEFgIDAQIeAQIXgAAK
    CRCWP6J3EEWFRUiADACai+xytv2keEFJWjXNnFAx6/obnHRcXOI3w6nH/zL8gNI7YN5jcdQT2NYv
    KVYTb3fWGuMsjHWgat5Gq3AtJrOKABpZ6qeYNPk0Axn/dKtOTwXjZ4pKX3bbUYvVfs0fCEZvB0HH
    Ij2wI9kgMpoTrkj22LE8layZTPOoQ+3/FbLzS8hN3CYZj25mHN7bpZq8EbV38FW9EU0HM0tg6Cvo
    xkRiVqAuAC0KnVIZAdhD4dlYKuncq64nMvT1A5wxSYbnE+ufmnWQQhhS6BOwRqN054yw1FrWNDFs
    vnOSHmr8dIiriv+aZYvx5JQFJ7oZP3LwdYygocQcAJA8HFTIk3P6uJiIF/zdDzocgdKs+IYDoId0
    hxX7sGCvqdrsveq8n3m7uQiN7FvSiV0eXIdV4F7340kc8EKiYwpuYSaZX0UWKLenzlUvD+W4pZCW
    toXzPsW7PKUtq1xdW0+NY+AGLCvSJCc5F4S5kFCObfBAYBbldjwwJFocdq/YOvvWYTPyV7kJeJS5
    AY0EZOeGaQEMALNIFUricEIwtZiX7vSDjwxobbqPKqzdek8x3ud0CyYlrbGHy0k+FDEXstjJQQ1s
    9rjJSu3sv5wyg9GDAUH3nzO976n/ZZvKPti3p2XU2UFx5gYkaaFVD56yYxqGY0YU5ft6BG+RUz3i
    EPg3UBUzt0sCIYnG9+CsDqGOnRYIIa46fu2/H9Vu8JvvSq9xbsK9CfoQDkIcoQOixPuI4P7eHtsw
    CeYR/1LUTWEnYQWsBCf57cEpzR6t7mlQnzQo9z4i/kp4S0ybDB77wnn+isMADOS+/VpXO+M7Zj5t
    pfJ6PkKch3SGXdUy3zht8luFOYpJr2lVzp7n3NwB4zW08RptTzTgFAaW/NH2JjYI+rDvQm4jNs08
    Dtspnm4OQvBA9Df/6qwMEOZ9i10ixqk+55UpQFJ3nf4uKlSUM7bKXXVcD/odq804Y/K4y3csE059
    YVIyaPexEvYSYlHE2odJWRg2Q1VehmrOSC8Qps3xpU7dTHXD74ZpaYbrhaViRS5v/lCsiwARAQAB
    iQG8BBgBCgAmFiEEtTrne622MKaDBGAFlj+idxBFhUUFAmTnhmkCGwwFCQPCZwAACgkQlj+idxBF
    hUUNbQv8DCcfi3GbWfvp9pfY0EJuoFJXLNgci7z7smXq7aqDp2huYQ+MulnPAydjRCVW2fkHItF2
    Ks6l+2/8t5Xz0eesGxSTxTyR31ARENMXaq78Lq+itZ+usOSDNuwJcEmJM6CceNMLs4uFkX2GRYhc
    hkry7P0ClkLxUTiB43ooi+CqILtlNxH7kM1O4Ncs6UGZMXf2IiG9s3JDCsYVPkC5QDMOPkTy2Zri
    F56uPerlJveF0dC61RZ6RlM3iSJ9Fwvea0Oy4rwkCcs5SHuwoDTFyxiyz0QC9iqi3fG3iSbLvY9U
    tJ6X+BtDqdXLAT9Pq527mukPP3LwpEqFVyNQKnGLdLOu2YXcTWWWseSQkHRzBmjD18KTD74mg4aX
    xEabyT4snrXpi5+UGLT4KXGV5syQO6Lc0OGw9O/0qAIU+YW7ojbKv8fr+NB31TGhGYWASjYlN1Nv
    PotRAK6339O0/Rqr9xGgy3AYSR+ic2Y610IM7xccKuTVAW9UofKQwJZChqae9VVZ
