# vim:ts=2:sw=2:et:ai:sts=2
---
# =============================================================================
# Reusable defaults for all hosts.
# =============================================================================

# Default domain name to construct URLs.
domain_name: ~
# Default domain name to append to inventory hosts.
inventory_domain_name: '{{ domain_name }}'

# Canonical hostname and FQDN.
host_name: '{{ inventory_hostname_short }}'
host_fqdn: '{{ inventory_hostname_short }}.{{ inventory_domain_name }}'

# General network parameters.
# -----------------------------------------------------------------------------
nameservers:
  - 8.8.8.8

# Networks directly connected to this host.
local_networks: []
# Private/internal, not globally routable networks.
internal_networks: []
# Link-local addressed networks.
link_local_networks:
  - 169.254/16
  - 'fe80::/10'

# Trusted private networks.
# -----------------------------------------------------------------------------
trusted_networks: '{{ internal_networks }}'

# Host environments.
# -----------------------------------------------------------------------------
envs:
  - prod
  - test
  - dev
env: |-
  {{
    (
      (group_names | intersect(envs)) or [None]
    ) | first
  }}
