# vim:ts=2:sw=2:et:ai:sts=2
---
# =============================================================================
# Reusable defaults for apache2 role.
# =============================================================================

apache2__enable: false
apache2__install_ferm_svc: '{{ ferm__enable | bool }}'
apache2__listen_http__base: [80]
apache2__listen_https__base: []
apache2__logdirs__base:
  - /var/log/apache2

# Configurable settings for these templates.
# -----------------------------------------------------------------------------

# Enable the `MD` module for automatic SSL certificate creation.
apache2__use_md: false

# Certificate directory for the default SSL site (when not using `MD`).
apache2__default_ssl_cert_path: |-
  {{ '%s/%s' % (dehydrated__cert_path, host_fqdn) }}

# Generated templates
# -----------------------------------------------------------------------------

apache2__mods__base:
  rewrite:
    state: enabled

apache2__sites__base:
  000-default:
    state: enabled
    src: |
      <VirtualHost *:80>
        ServerAdmin webmaster@{{ domain_name }}
        DocumentRoot /var/www/html

        ErrorLog ${APACHE_LOG_DIR}/error.log
        CustomLog ${APACHE_LOG_DIR}/access.log combined

        RewriteEngine On
        RewriteRule ^/.well-known/acme-challenge/.* - [L]
        RewriteCond %{HTTPS} off
        RewriteRule (.*) https://%{HTTP_HOST}%{REQUEST_URI}
      </VirtualHost>

apache2__listen_https__ssl: [443]

apache2__mods__ssl:
  md:
    state:  |-
      {{ 'enabled' if apache2__use_md else 'absent' }}
  ssl:
    state: enabled

apache2__conf__ssl:
  md:
    state:  |-
      {{ 'enabled' if apache2__use_md else 'absent' }}
    src: |
      MDCertificateAgreement accepted

apache2__sites__ssl:
  001-default-ssl:
    state: |-
      {{
        'enabled' if apache2__use_md or dehydrated__enable else 'absent'
      }}
    src: |
      {% if apache2__use_md %}
      MDomain {{ host_fqdn }}
      {% endif %}

      <VirtualHost *:443>
        ServerName {{ host_fqdn }}
        ServerAdmin webmaster@{{ domain_name }}
        DocumentRoot /var/www/html

        ErrorLog ${APACHE_LOG_DIR}/error.log
        CustomLog ${APACHE_LOG_DIR}/access.log combined

        SSLEngine On
      {% if not apache2__use_md %}
        SSLCertificateFile      {{ apache2__default_ssl_cert_path }}/cert.pem
        SSLCertificateKeyFile   {{ apache2__default_ssl_cert_path }}/privkey.pem
        SSLCertificateChainFile {{ apache2__default_ssl_cert_path }}/chain.pem
      {% endif %}
      </VirtualHost>
