# vim:ts=2:sw=2:et:ai:sts=2
---
# =============================================================================
# Defaults for dropbear-initramfs role.
# =============================================================================

dropbear_initramfs__enable: false

# Allow all admin users to connect to the initramfs.
dropbear_initramfs__authorized_keys: |-
  {{
    users__admins_from_def |
    map("extract", users__local_defs, "authorized") |
    select("defined") |
    sum(start=[])
  }}
