# vim:ts=2:sw=2:et:ai:sts=2
---
# =============================================================================
# Reusable defaults and templates for restic_backup role.
# =============================================================================

restic_backup__enable: false
