# vim:ts=2:sw=2:et:ai:sts=2
---
# =============================================================================
# Reusable defaults and templates for simple_bind role.
# =============================================================================

simple_bind__enable: false
simple_bind__install_ferm_svc: '{{ ferm__enable | bool }}'
