# vim:ts=2:sw=2:et:ai:sts=2

# Role: Manage dropbear-initramfs authorized keys.
---
- name: Install package
  ansible.builtin.package:
    name: dropbear-initramfs
    state: present

- name: Update the list of authorized keys
  ansible.posix.authorized_key:
    user: root
    state: present
    # Important: double quotes scalar is needed here so that '\n'.join()
    # uses actual newlines, and not literal r'\n'.
    # yamllint disable-line rule:quoted-strings
    key: "{{ '\n'.join(dropbear_initramfs__authorized_keys) }}"
    path: '{{ dropbear_initramfs__authorized_keys_file }}'
    manage_dir: false
    exclusive: true
  notify: _tina_update_initramfs

- name: Set boot-time network parameters
  ansible.builtin.lineinfile:
    dest: '{{ dropbear_initramfs__conf_file }}'
    line: IP={{ dropbear_initramfs__ipconfig }}
    regexp: '^IP[ =]'
    state: present
  notify: _tina_update_initramfs
  when: dropbear_initramfs__ipconfig is ansible.builtin.truthy
