# vim:ts=2:sw=2:et:ai:sts=2
---

loki__http_listen_port: 3100
loki__grpc_listen_port: 9096
loki__storage_dir: /var/lib/loki

ferm__services__loki:
  loki-http:
    dport: 3100
    proto: tcp
    saddr: '{{ internal_networks }}'
  loki-grpc:
    dport: 9096
    proto: tcp
    saddr: '{{ internal_networks }}'

