# vim:ts=2:sw=2:et:ai:sts=2
---

apt__packages_to_install__loki:
  - loki
apt__services_to_enable__loki:
  - loki
apt__services_to_start__loki:
  - loki

ferm__services__loki:
  loki-http:
    dport: 3100
    proto: tcp
    saddr: '{{ internal_networks }}'
  loki-grpc:
    dport: 9096
    proto: tcp
    saddr: '{{ internal_networks }}'
