# vim:ts=2:sw=2:et:ai:sts=2
---
argument_specs:
  main:
    short_description: Install and configure Prometheus exporter for PostgreSQL
    author:
      - Martina Ferrari
    options:
      postgres_exporter__listen_addr:
        description: Address to listen on for web interface and telemetry.
        type: str
        default: ''

      postgres_exporter__listen_port:
        description: Port to listen on for web interface and telemetry.
        type: int
        default: 9187

      postgres_exporter__data_source_uri:
        description:
          - Database connection string.
          - Accepts URI form and key=value form arguments.
            The URI may contain the username and password to connect with.
        type: str
        default: /postgres?host=/run/postgresql

      postgres_exporter__data_source_user:
        description: Connection username.
        type: str
        default: prometheus

      postgres_exporter__data_source_pass:
        description: Connection username.
        type: str
        default: ''

      postgres_exporter__custom_queries:
        description: Custom queries to run.
        type: dict

      postgres_exporter__custom_queries_path:
        description: Path to custom queries file.
        type: str
        default: /etc/prometheus/postgres_exporter_queries.yaml

      postgres_exporter__extra_args:
        description: Extra command-line arguments for the server.
        type: str

      postgres_exporter__install_ferm_svc:
        description: Install ferm configuration file.
        type: bool
        default: false

      postgres_exporter__ferm_allow_from:
        description: Optionally limit access by a list of IP addresses/blocks.
        type: list
        elements: str
