# vim:ts=2:sw=2:et:ai:sts=2
---

_promtail_clients_from_urls: |-
  {% filter from_yaml_all %}
  {% for url in promtail__client_urls %}
  {{
    promtail__client_defaults | combine(dict(url=url)) |
    to_yaml(explicit_start=True)
  }}
  {% endfor %}
  {% endfilter %}
