# vim:ts=2:sw=2:et:ai:sts=2
---

_promtail_clients_from_urls: |
  {% set res = [] %}
  {% for url in promtail__client_urls %}
  {% set _ = res.append(promtail__client_defaults | combine(dict(url=url))) %}
  {% endfor %}
  {{- res -}}
