# vim:ts=2:sw=2:et:ai:sts=2
---

loki__http_listen_port: 3100
loki__grpc_listen_port: 9096
loki__storage_dir: /var/lib/loki

# If true, install ferm configuration file.
loki__install_ferm_svc: '{{ ferm__enable | bool }}'
# Optionally limit access to a list of IP addresses.
loki__http_ferm_allow_from: '{{ internal_networks }}'
loki__grpc_ferm_allow_from: '{{ internal_networks }}'
