# vim:ts=2:sw=2:et:ai:sts=2

# Role: Configure loki.
---
- name: Install required packages
  ansible.builtin.package:
    name:
      - loki
      - logcli
    state: present

- name: Create '{{ loki__storage_dir }}'
  ansible.builtin.file:
    path: '{{ loki__storage_dir }}'
    state: directory
    owner: loki
    group: nogroup
    mode: '0755'

- name: Configure loki
  ansible.builtin.template:
    src: config.yml.j2
    dest: /etc/loki/config.yml
    owner: root
    group: root
    mode: '0644'
  notify: _tina_restart_loki

- name: Install ferm configuration
  ansible.builtin.template:
    src: ferm.conf.j2
    dest: /etc/ferm/ferm.d/loki.conf
    owner: root
    group: adm
    mode: '0644'
  notify: _tina_reload_ferm
  when: loki__install_ferm_svc

- name: Start and enable service
  ansible.builtin.service:
    name: loki
    state: started
    enabled: true
