# vim:ts=2:sw=2:et:ai:sts=2
---
- name: Install needed packages
  ansible.builtin.package:
    name:
      - bind9
      - bind9-dnsutils
      - bind9-utils
    state: present

- name: Copy Bind9 configurations
  ansible.builtin.copy:
    src: '{{ item }}'
    dest: /etc/bind/
    owner: root
    group: bind
    mode: '0644'
    force: true
  with_fileglob:
    - '{{ bind_config__conf_files }}'
  loop_control:
    label: '{{ item | basename }}'
  notify:
    - _tina_validate_bind9_conf
    - _tina_reload_bind9

- name: Install ferm configuration
  ansible.builtin.template:
    src: ferm.conf.j2
    dest: /etc/ferm/ferm.d/bind.conf
    owner: root
    group: adm
    mode: '0644'
  notify: _tina_reload_ferm
  when: _bind_config_install_ferm_svc

- name: Start and enable service
  ansible.builtin.service:
    name: bind9
    state: started
    enabled: true
