# vim:ts=2:sw=2:et:ai:sts=2
---

# If true, install ferm configuration file.
grafana__install_ferm_svc: false
# Optionally limit access to a list of IP addresses.
grafana__ferm_allow_from: ~

grafana__server__http_port: 3000
grafana__server__domain: localhost
grafana__server__root_url: https://%(domain)s/

grafana__analytics__reporting_enabled: false

grafana__users__allow_sign_up: false

grafana__auth_anonymous__enabled: false
grafana__auth_ldap__enabled: false
grafana__auth_basic__enabled: true

grafana__smtp__enabled: true
grafana__smtp__host: localhost:25
# The email address from which the server will send messages (the domain
# is the hostname).
grafana__smtp__from_address: grafana@localhost

# Send a welcome email with a link to the first authorization step.
grafana__emails__welcome_email_on_sign_up: true

# Allow the use of experimental plugins.
grafana__plugins__enable_alpha: true
# Meta Queries plugin is built as a data source plugin and can be used in
# conjunction with other data source to show computed metrics like Moving
# Average, Time Shift.
grafana__plugins__allow_unsigned: goshposh-metaqueries-datasource

# LDAP configuration
grafana__ldap__servers__host: localhost
grafana__ldap__servers__port: 389
grafana__ldap__servers__use_ssl: false
grafana__ldap__servers__start_tls: false
grafana__ldap__servers__ssl_skip_verify: false
grafana__ldap__servers__bind_dn: ~

grafana__ldap__servers__password: ~
grafana__ldap__servers__search_filter: ~
grafana__ldap__servers__base_dns: ~

grafana__ldap__servers_atributes__name: givenName
grafana__ldap__servers_atributes__surname: sn
grafana__ldap__servers_atributes__username: cn
grafana__ldap__servers_atributes__member_of: memberOf
grafana__ldap__servers_atributes__email: mail
grafana__ldap__servers_group_mappings:
  - group_dn: cn=admins,ou=groups,dc=grafana,dc=org
    org_role: Admin
  - group_dn: cn=users,ou=groups,dc=grafana,dc=org
    org_role: Editor
  - group_dn: '*'
    org_role: Viewer
