# vim:ts=2:sw=2:et:ai:sts=2
---
- name: _tina_restart_loki
  ansible.builtin.service:
    name: loki
    state: restarted
- name: _tina_reload_ferm
  ansible.builtin.service:
    name: ferm
    state: reloaded
