# vim:ts=2:sw=2:et:ai:sts=2
---
# =============================================================================
# Install and configure Apache web server.
# =============================================================================

- name: Install and configure Apache web server
  hosts: '{{ target_hosts | d("all") }}'
  become: true
  gather_facts: false
  roles:
    - role: tina_pm.common.apache2
      when: apache2__enable
      tags: apache2
