# vim:ts=2:sw=2:et:ai:sts=2

# Playbook: Configure APT distribution, sources, PGP keys, and preferences;
# and install required packages.
---
- name: Configure APT and install required packages
  hosts: all
  become: true
  gather_facts: true
  roles:
    - role: tina_pm.common.apt
      tags: apt
      vars:
        # QEMU guest agent will disconnect during an upgrade.
        libvirt__vm_use_qemu_connection: false
