# vim:ts=2:sw=2:et:ai:sts=2
---
# =============================================================================
# Run the equivalent of `apt dist-upgrade --autoremove --purge`.
# Will also configure APT according to role settings.
# =============================================================================

- name: Upgrade packages
  hosts: '{{ target_hosts | d("all") }}'
  become: true
  gather_facts: true
  roles:
    - role: tina_pm.common.apt
      when: apt__enable
      tags: apt
      vars:
        apt__run_upgrade: true
        apt__run_autoremove: true
        apt__purge_removed: true
        # QEMU guest agent will disconnect during an upgrade.
        libvirt__vm_use_qemu_connection: false
