# vim:ts=2:sw=2:et:ai:sts=2

# Playbook: Install and configure aptly.
---
- name: Install and configure aptly
  hosts: all
  become: true
  gather_facts: false
  roles:
    - role: tina_pm.playbooks.aptly
      when: aptly__enable
      tags: aptly
