# vim:ts=2:sw=2:et:ai:sts=2
---
# =============================================================================
# Install and configure aptly Debian repository manager.
# =============================================================================

- name: Install and configure aptly Debian repository manager
  hosts: '{{ target_hosts | d("all") }}'
  become: true
  gather_facts: false
  roles:
    - role: tina_pm.playbooks.aptly
      when: aptly__enable
      tags: aptly
