# vim:ts=2:sw=2:et:ai:sts=2

# Playbook: Clone sysadmin repository for configuration reuse.
---
- name: Install and configure aptly
  hosts: aptly_servers
  become: true
  vars:
    aptly__repo_path: /srv/debian
    aptly__repo_www_path: /srv/www/aptly/html/
    aptly__repo_owner: root
    aptly__repo_group: debrepo
  tasks:
    - name: Install needed packages
      ansible.builtin.package:
        name:
          - aptly
        state: present

    - name: Create Debian repo directories
      ansible.builtin.file:
        state: directory
        dest: '{{ item }}'
        owner: '{{ aptly__repo_owner }}'
        group: '{{ aptly__repo_group }}'
        mode: u=rwX,g=rwX,o=rX
      loop:
        - '{{ aptly__repo_path }}'
        - '{{ aptly__repo_www_path }}'

    - name: Set extended permissions
      ansible.posix.acl:
        state: present
        path: '{{ item }}'
        default: false
        etype: group
        entity: '{{ aptly__repo_group }}'
        permissions: rwX
      loop:
        - '{{ aptly__repo_path }}'
        - '{{ aptly__repo_www_path }}'

    - name: Set default extended permissions
      ansible.posix.acl:
        state: present
        path: '{{ item }}'
        default: true
        etype: group
        entity: '{{ aptly__repo_group }}'
        permissions: rwX
      loop:
        - '{{ aptly__repo_path }}'
        - '{{ aptly__repo_www_path }}'

    - name: Configure aptly
      ansible.builtin.template:
        src: files/aptly/aptly.conf.j2
        dest: /etc/aptly.conf
        owner: root
        group: root
        mode: '0644'

    - name: Find existing repos
      ansible.builtin.command:
        argv:
          - aptly
          - repo
          - list
          - -raw
      register: _aptly_repos
      check_mode: false
      changed_when: false

    - name: Create repos
      ansible.builtin.command:
        argv:
          - aptly
          - repo
          - create
          - -distribution={{ item }}
          - -component=main
          - '{{ item }}'
      loop: '{{ aptly__repo_dists | difference(_aptly_repos.stdout_lines) }}'

    - name: Publish repos
      ansible.builtin.command:
        argv:
          - aptly
          - publish
          - repo
          - -architectures=source,amd64
          - '{{ item }}'
          - 'filesystem:{{ aptly__repo_prefix }}:'
        creates: '{{ aptly__repo_www_path }}/dists/{{ item }}/Release'
      loop: '{{ aptly__repo_dists }}'
