# vim:ts=2:sw=2:et:ai:sts=2
---
# =============================================================================
# Set up host base configuration.
# =============================================================================

- name: Set up host base configuration
  hosts: '{{ target_hosts | d("all") }}'
  become: true
  gather_facts: true
  roles:
    - role: tina_pm.common.base_setup
      when: base_setup__enable
      tags: base_setup
