# vim:ts=2:sw=2:et:ai:sts=2

# Playbook: Install and manage Bind9 configuration.
---
- name: Install and manage Bind9 configuration
  hosts: '{{ target_hosts | d("all") }}'
  become: true
  gather_facts: false
  roles:
    - role: tina_pm.playbooks.bind_config
      when: bind_config__enable
      tags: bind_config
