# vim:ts=2:sw=2:et:ai:sts=2

# Playbook: Update dropbear initramfs authorized key.
---
- name: Update dropbear initramfs authorized keys
  hosts: libvirt_hosts
  become: true

  tasks:
    - name: Update the list of authorized keys
      ansible.posix.authorized_key:
        user: root
        state: present
        # Important: double quotes scalar is needed here so that '\n'.join()
        # uses actual newlines, and not literal r'\n'.
        # yamllint disable-line rule:quoted-strings
        key: "{{ '\n'.join(dropbear_initramfs__authorized_keys) }}"
        path: '{{ dropbear_initramfs__authorized_keys_file }}'
        manage_dir: false
        exclusive: true
      notify: Update initramfs

  handlers:
    - name: Update initramfs
      ansible.builtin.command:
        cmd: /usr/sbin/update-initramfs -u
      changed_when: true
