# vim:ts=2:sw=2:et:ai:sts=2
---
# =============================================================================
# Install and configure fail2ban automatic IP address banner
# =============================================================================

- name: Install and configure fail2ban automatic IP address banner
  hosts: '{{ target_hosts | d("all") }}'
  become: true
  gather_facts: false
  roles:
    - role: tina_pm.common.fail2ban
      when: ferm__enable and fail2ban__enable
      tags: [ferm, fail2ban]
