# vim:ts=2:sw=2:et:ai:sts=2
---
- name: Install and configure ferm
  hosts: '{{ target_hosts | d("all") }}'
  gather_facts: false
  become: true
  roles:
    - role: tina_pm.common.ferm
      when: ferm__enable
      tags: ferm
