# vim:ts=2:sw=2:et:ai:sts=2

# Playbook: Install and configure fast and lightweight LDAP server.
---
- name: Install and configure fast and lightweight LDAP server
  hosts: all
  gather_facts: false
  become: true
  roles:
    - role: tina_pm.common.glauth
      when: glauth__enable
      tags: [ldap]
