# vim:ts=2:sw=2:et:ai:sts=2

# Playbook: Set up and configure grafana.
#
#   - If a local ldap server is available,
#     it will be configured as default auth method.
---
- name: Set up and configure grafana
  hosts: grafana_servers
  become: true

  tasks:
    - name: Execute apt role for sources configuration
      ansible.builtin.include_role:
        name: tina_pm.common.apt

    - name: Install package
      ansible.builtin.package:
        name: grafana
        state: present

    - name: Configure grafana
      ansible.builtin.template:
        src: files/grafana/grafana.ini.j2
        dest: /etc/grafana/grafana.ini
        owner: root
        group: grafana
        mode: '0640'
      notify: _tina_restart_grafana

    - name: Configure ldap server if available
      ansible.builtin.template:
        src: files/grafana/ldap.toml.j2
        dest: /etc/grafana/ldap.toml
        owner: root
        group: grafana
        mode: '0640'
      when: glauth__service_ldap.enabled | default()
      notify: _tina_restart_grafana

    - name: Start and enable service
      ansible.builtin.service:
        name: grafana-server
        state: started
        enabled: true

  handlers:
    - name: _tina_restart_grafana
      ansible.builtin.service:
        name: grafana-server
        state: restarted
