# vim:ts=2:sw=2:et:ai:sts=2
---
# =============================================================================
# Install and configure loki log collector and analyser.
# =============================================================================

- name: Install and configure loki log collector and analyser
  hosts: loki_servers
  become: true
  gather_facts: false
  roles:
    - role: tina_pm.playbooks.loki
