# vim:ts=2:sw=2:et:ai:sts=2
---
# =============================================================================
# Install and configure monitoring stack components:
#
#  * Grafana observability and data visualization platform.
#  * Prometheus monitoring system and timeseries database.
#  * Prometheus node exporter.
#  * Prometheus blackbox exporter.
#  * Prometheus PostgreSQL exporter.
#  * Mtail monitoring data extractor from logs.
#  * Loki log collector and analyser.
#  * Promtail log collection agent
# =============================================================================

- name: Install and configure monitoring stack components
  hosts: '{{ target_hosts | d("all") }}'
  become: true
  gather_facts: false
  roles:
    - role: tina_pm.common.prometheus_node_exporter
      when: node_exporter__enable
      tags: [monitoring, node_exporter]

    - role: tina_pm.common.mtail
      when: mtail__enable
      tags: [monitoring, mtail]

    - role: tina_pm.common.prometheus_blackbox_exporter
      when: blackbox_exporter__enable
      tags: [monitoring, blackbox_exporter]

    - role: tina_pm.playbooks.postgres_exporter
      when: postgres_exporter__enable
      tags: [monitoring, postgres_exporter]

    - role: tina_pm.common.prometheus
      when: prometheus__enable
      tags: [monitoring, prometheus]

    - role: tina_pm.playbooks.grafana
      when: grafana__enable
      tags: [monitoring, grafana]

    - role: tina_pm.playbooks.loki
      when: loki__enable
      tags: [monitoring, loki]

    - role: tina_pm.playbooks.promtail
      when: promtail__enable
      tags: [monitoring, promtail]
