# vim:ts=2:sw=2:et:ai:sts=2

# Playbook: Set up Prometheus, Grafana, `node_exporter`, `mtail` and `blackbox
# exporter`.
---
- name: Set up monitoring stack
  hosts: '{{ target_hosts | d("all") }}'
  gather_facts: false
  become: true

  roles:
    - role: tina_pm.common.prometheus_node_exporter
      when: node_exporter__enable
      tags: [monitoring, node-exporter]

    - role: tina_pm.common.mtail
      when: mtail__enable
      tags: [monitoring, mtail]

    - role: tina_pm.common.prometheus_blackbox_exporter
      when: blackbox_exporter__enable
      tags: [monitoring, blackbox-exporter]

    - role: tina_pm.common.prometheus
      when: inventory_hostname in groups['prometheus_servers']
      tags: [monitoring, prometheus]

    - role: tina_pm.playbooks.grafana
      when: grafana__enable
      tags: [monitoring, grafana]
