# vim:ts=2:sw=2:et:ai:sts=2

# Playbook: Set up Prometheus, `node_exporter`, `mtail` and `blackbox exporter`.
---
- name: Set up prometheus node_exporter
  hosts: all
  roles:
    - role: tina_pm.common.prometheus_node_exporter
      when: node_exporter__enable
      tags: [prometheus, node-eporter]

- name: Set up mtail log extractor
  hosts: all
  roles:
    - role: tina_pm.common.mtail
      when: mtail__enable
      tags: [prometheus, mtail]

- name: Install and configure prometheus
  hosts: all
  roles:
    - role: tina_pm.common.prometheus
      when: inventory_hostname in groups['prometheus_servers']
      tags: prometheus

- name: Set up blackbox exporter prober
  hosts: all
  roles:
    - role: tina_pm.common.prometheus_blackbox_exporter
      when: blackbox_exporter__enable
      tags: [prometheus, blackbox-exporter]
