# vim:ts=2:sw=2:et:ai:sts=2
---
# =============================================================================
# Install and configure monitoring stack components:
#
#  * Grafana observability and data visualization platform.
#  * Prometheus monitoring system and timeseries database.
#  * Prometheus node exporter.
#  * Prometheus blackbox exporter.
#  * Mtail monitoring data extractor from logs.
#  * Loki log collector and analyser.
#  * Promtail log collection agent
# =============================================================================

- name: Install and configure monitoring stack components
  hosts: '{{ target_hosts | d("all") }}'
  become: true
  gather_facts: false
  roles:
    - role: tina_pm.common.prometheus_node_exporter
      when: node_exporter__enable
      tags: [monitoring, node-exporter]

    - role: tina_pm.common.mtail
      when: mtail__enable
      tags: [monitoring, mtail]

    - role: tina_pm.common.prometheus_blackbox_exporter
      when: blackbox_exporter__enable
      tags: [monitoring, blackbox-exporter]

    - role: tina_pm.common.prometheus
      when: inventory_hostname in groups.get('prometheus_servers', [])
      tags: [monitoring, prometheus]

    - role: tina_pm.playbooks.grafana
      when: grafana__enable
      tags: [monitoring, grafana]

    - role: tina_pm.playbooks.loki
      when: inventory_hostname in groups.get('loki_servers', [])
      tags: [monitoring, loki]

- name: Install and configure promtail log collection agent
  import_playbook: ./promtail.yaml
