# vim:ts=2:sw=2:et:ai:sts=2

# Playbook: configure network interfaces.
---
- name: Configure network interfaces
  hosts: '{{ target_hosts | d("all") }}'
  become: true
  gather_facts: false
  roles:
    - role: tina_pm.common.net
      when: net__enable
      tags: net
