# vim:ts=2:sw=2:et:ai:sts=2
---
# =============================================================================
# Apply core networking configuration:
#
#  * Configure network interfaces.
#  * Configure the DNS resolver.
#  * Install and configure ferm firewall manager.
#  * Install and configure tinc VPN daemon.
# =============================================================================

- name: Configure network interfaces
  import_playbook: ./net.yaml

- name: Configure the DNS resolver
  import_playbook: ./resolv.yaml

- name: Install and configure Ferm firewall manager
  import_playbook: ./ferm.yaml

- name: Install and configure tinc VPN daemon
  import_playbook: ./tinc.yaml
