# vim:ts=2:sw=2:et:ai:sts=2

# Playbook: Set up network time syncronization.
---
- name: Set up network time syncronization
  hosts: '{{ target_hosts | d("all") }}'
  gather_facts: true
  become: true
  roles:
    - role: tina_pm.third_party.ntp
      when: ntp_enabled
      tags: ntp
