# vim:ts=2:sw=2:et:ai:sts=2
---
# =============================================================================
# Install and configure PostgreSQL object-relational SQL database.
# =============================================================================

- name: Install and configure PostgreSQL object-relational SQL database
  hosts: '{{ target_hosts | d("all") }}'
  become: true
  gather_facts: true
  roles:
    - role: tina_pm.third_party.postgresql
      when: postgresql__enable
      tags: postgresql

    - role: tina_pm.third_party.postgresql_objects
      become_user: postgres
      when: postgresql__enable
      tags: [postgresql, postgresql_objects]

  tasks:
    - name: Install ferm configuration
      ansible.builtin.include_role:
        name: tina_pm.common.ferm_svc
      vars:
        ferm_svc__name: postgresql
        ferm_svc__allow_protos: tcp
        ferm_svc__allow_from: '{{ postgresql__ferm_allow_from }}'
        ferm_svc__allow_ports: '{{ postgresql__ferm_allow_ports }}'
      when: postgresql__enable and postgresql__install_ferm_svc | bool
