# vim:ts=2:sw=2:et:ai:sts=2
---
# =============================================================================
# Configure the DNS resolver.
# =============================================================================

- name: Configure the DNS resolver
  hosts: '{{ target_hosts | d("all") }}'
  become: true
  gather_facts: false
  roles:
    - role: tina_pm.third_party.resolv
      when: resolv__enable
      tags: resolv
