# vim:ts=2:sw=2:et:ai:sts=2
---
# =============================================================================
# Set up backups with Restic.
# =============================================================================

- name: Set up backups with Restic
  hosts: '{{ target_hosts | d("all") }}'
  become: true
  gather_facts: false
  roles:
    - role: tina_pm.playbooks.restic_backup
      when: restic_backup__enable
      tags: [backup, restic_backup]
