# vim:ts=2:sw=2:et:ai:sts=2
---
# =============================================================================
# Install and configure Bind9 DNS server.
# =============================================================================

- name: Install and configure Bind9 DNS server
  hosts: '{{ target_hosts | d("all") }}'
  become: true
  gather_facts: false
  roles:
    - role: tina_pm.common.simple_bind
      when: simple_bind__enable
      tags: simple_bind
