# vim:ts=2:sw=2:et:ai:sts=2

# Playbook: Install bind9 server.
---
- name: Install bind9 server
  hosts: all
  gather_facts: false
  become: true
  roles:
    - role: tina_pm.common.simple_bind
      when: simple_bind__enable
      tags: simple_bind
