# vim:ts=2:sw=2:et:ai:sts=2
---
# =============================================================================
# Run all "safe" playbooks, excluding core networking changes.
# =============================================================================

- name: Set up user accounts and home directories
  import_playbook: ./users.yaml

- name: Set up host base configuration
  import_playbook: ./base_setup.yaml

- name: Manage remote disk unlocking with dropbear-initramfs
  import_playbook: ./dropbear_initramfs.yaml

- name: Configure APT and install required packages
  import_playbook: ./apt.yaml

- name: Set up network time syncronization
  import_playbook: ./ntp.yaml

- name: Install and configure Ferm firewall manager
  import_playbook: ./ferm.yaml

- name: Install and configure fail2ban automatic IP address banner
  import_playbook: ./fail2ban.yaml

- name: Install and configure Bind9 DNS server
  import_playbook: ./simple_bind.yaml

- name: Install Bind9 and deploy raw configuration files
  import_playbook: ./bind_config.yaml

- name: Configure the DNS resolver
  import_playbook: ./resolv.yaml

- name: Install and configure Apache web server
  import_playbook: ./apache2.yaml

- name: Install and configure monitoring stack components
  import_playbook: ./monitoring.yaml

- name: Install and configure GLAuth fast and lightweight LDAP server
  import_playbook: ./glauth.yaml

- name: Install and configure TheLounge web interface and bouncer for IRC
  import_playbook: ./thelounge.yaml
