---
- name: Install and configure TheLounge
  hosts: '{{ target_hosts | d("thelounge_servers") }}'
  become: true
  roles:
    - role: tina_pm.common.thelounge
      when: thelounge__enable
      tags: [thelounge]
