# vim:ts=2:sw=2:et:ai:sts=2
---
# =============================================================================
# Install and configure tinc VPN daemon.
# =============================================================================

- name: Install and configure tinc VPN daemon
  hosts: '{{ target_hosts | d("tinc_servers") }}'
  become: true
  gather_facts: true
  roles:
    - role: tina_pm.third_party.tinc
      tags: tinc
