# vim:ts=2:sw=2:et:ai:sts=2
---
# =============================================================================
# Set up user accounts and home directories.
# =============================================================================

- name: Set up user accounts and home directories
  hosts: '{{ target_hosts | d("all") }}'
  become: true
  gather_facts: true
  roles:
    - role: tina_pm.common.users
      when: users__enable
      tags: users
