# vim:ts=2:sw=2:et:ai:sts=2
---
- name: Set up user accounts and home directories
  hosts: '{{ target_hosts | d("all") }}'
  gather_facts: true
  become: true
  roles:
    - role: tina_pm.common.users
      tags: users
